name: Bump version
on:
  pull_request:
    branches:
      - main
      - maintance/**
      - release/**
      - hotfix/**
    types:
      - closed
      
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
          fetch-depth: '0'

      - name: Bump version and push tag
        id: tag_ver
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          PRERELEASE: false
          MAJOR_STRING_TOKEN: 'BREAKING CHANGE:'
          MINOR_STRING_TOKEN: 'FEAT:'
          PATCH_STRING_TOKEN: 'FIX:'
          NONE_STRING_TOKEN: 'NONE:' 
          DEFAULT_BUMP: 'none'
          INITIAL_VERSION: '0.3.0'
          RELEASE_BRANCHES: 'maintance/**,master,main,release/**'
        continue-on-error: true

      - name: Update version in pyproject toml
        if: steps.tag_ver.outcome == 'success'
        run: |
          sh ./tools/bump_version.sh ${{ steps.tag_ver.outputs.new_tag }}
    
      # Taken from here: 
      # https://gist.github.com/Broxzier/1ed980b8b3822d213e98042fc6a92040
      - name: Amend the last commit on version bumping
        if: steps.tag_ver.outcome == 'success'
        run: |
          git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
          git commit -a --amend --no-edit
          git push --force-with-lease
          echo "Complete"
          
